[package]
name = "day-24"
version = "0.1.0"
authors = ["Dan Stoza <dstoza@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-set = "0"
clap = "2"
common = { path = "../common" }